#!/usr/bin/env python3
"""Initialize the local writing environment."""

from __future__ import annotations

import argparse
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from hugo_blog.tools.hugo import DEFAULT_HUGO_VERSION, default_hugo_path, install_hugo
from hugo_blog.llm.client import DEEPSEEK_BASE_URL, load_dotenv


GENERATED_ENV_START = "# >>> hugo-blog local toolchain >>>"
GENERATED_ENV_END = "# <<< hugo-blog local toolchain <<<"
LLM_KEYS = ["LLM_PROVIDER", "LLM_BASE_URL", "LLM_MODEL", "LLM_API_KEY"]


def parse_hugo_version(output: str) -> str | None:
    match = re.search(r"hugo v?(\d+\.\d+\.\d+)", output)
    return match.group(1) if match else None


def run_command(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )


def hugo_version(hugo_bin: Path | str) -> str | None:
    result = run_command([str(hugo_bin), "version"])
    if result.returncode != 0:
        return None
    return parse_hugo_version(result.stdout)


def ensure_uv_environment() -> Path:
    if shutil.which("uv") is None:
        raise RuntimeError("uv is not installed or not available in PATH")

    print("Syncing Python environment with uv...")
    result = subprocess.run(["uv", "sync"], cwd=PROJECT_ROOT, check=False)
    if result.returncode != 0:
        raise RuntimeError("uv sync failed")

    python_name = "python.exe" if os.name == "nt" else "python"
    python_bin = PROJECT_ROOT / ".venv" / ("Scripts" if os.name == "nt" else "bin") / python_name
    if not python_bin.exists():
        raise RuntimeError(f"Python executable not found: {python_bin}")
    return python_bin


def ensure_hugo(version: str) -> Path:
    local_hugo = default_hugo_path(PROJECT_ROOT)
    candidates: list[Path] = []
    if local_hugo.exists():
        candidates.append(local_hugo)

    system_hugo = shutil.which("hugo")
    if system_hugo:
        candidates.append(Path(system_hugo))

    for candidate in candidates:
        candidate_version = hugo_version(candidate)
        if candidate_version == version:
            print(f"Using Hugo {candidate_version}: {candidate}")
            return candidate
        if candidate_version:
            print(f"Ignoring Hugo {candidate_version}, expected {version}: {candidate}")

    print(f"Installing Hugo {version} into .tools...")
    hugo_bin = install_hugo(version=version, project_root=PROJECT_ROOT, force=True)
    installed_version = hugo_version(hugo_bin)
    if installed_version != version:
        raise RuntimeError(f"Installed Hugo {installed_version}, expected {version}")
    return hugo_bin


def build_shell_env(
    *,
    base_env: dict[str, str],
    project_root: Path,
    python_bin: Path,
    hugo_bin: Path,
) -> dict[str, str]:
    env = dict(base_env)
    venv = python_bin.parent.parent
    path_entries = [str(python_bin.parent), str(hugo_bin.parent)]
    existing_path = env.get("PATH", "")

    env["BLOG_PROJECT_ROOT"] = str(project_root)
    env["VIRTUAL_ENV"] = str(venv)
    env["PYTHON"] = str(python_bin)
    env["HUGO_BIN"] = str(hugo_bin)
    env["PATH"] = ":".join([*path_entries, existing_path]) if existing_path else ":".join(path_entries)
    env.pop("PYTHONHOME", None)
    return env


def build_env_content(
    *,
    project_root: Path,
    python_bin: Path,
    hugo_bin: Path,
    env: dict[str, str] | None = None,
) -> str:
    env = env or build_shell_env(
        base_env=os.environ,
        project_root=project_root,
        python_bin=python_bin,
        hugo_bin=hugo_bin,
    )
    lines = [
        "# Generated by init.py. Source this block to use the project-local toolchain in a shell.",
        "unset PYTHONHOME",
        f'export BLOG_PROJECT_ROOT={shlex.quote(env["BLOG_PROJECT_ROOT"])}',
        f'export VIRTUAL_ENV={shlex.quote(env["VIRTUAL_ENV"])}',
        f'export PYTHON={shlex.quote(env["PYTHON"])}',
        f'export HUGO_BIN={shlex.quote(env["HUGO_BIN"])}',
        f'export PATH={shlex.quote(env["PATH"])}',
        "",
    ]
    return "\n".join(lines)


def merge_env_content(*, existing: str, generated: str) -> str:
    pattern = re.compile(
        rf"{re.escape(GENERATED_ENV_START)}.*?{re.escape(GENERATED_ENV_END)}\n?",
        re.DOTALL,
    )
    preserved = pattern.sub("", existing).strip()
    generated_block = f"{GENERATED_ENV_START}\n{generated.rstrip()}\n{GENERATED_ENV_END}"
    if preserved:
        return f"{preserved}\n\n{generated_block}\n"
    return f"{generated_block}\n"


def missing_llm_config(values: dict[str, str]) -> list[str]:
    normalized = {
        "LLM_PROVIDER": values.get("LLM_PROVIDER") or "deepseek",
        "LLM_BASE_URL": values.get("LLM_BASE_URL") or DEEPSEEK_BASE_URL,
        "LLM_MODEL": values.get("LLM_MODEL", ""),
        "LLM_API_KEY": values.get("LLM_API_KEY", ""),
    }
    return [key for key in LLM_KEYS if not normalized.get(key, "").strip()]


def build_llm_env_content(values: dict[str, str]) -> str:
    lines = ["# LLM metadata generation"]
    for key in LLM_KEYS:
        value = values.get(key, "")
        lines.append(f'{key}="{value}"')
    return "\n".join(lines) + "\n"


def _set_env_value(content: str, key: str, value: str) -> str:
    line = f'{key}="{value}"'
    pattern = re.compile(rf"^(?:export\s+)?{re.escape(key)}=.*$", re.MULTILINE)
    if pattern.search(content):
        return pattern.sub(line, content)
    if content and not content.endswith("\n"):
        content += "\n"
    return f"{content}{line}\n"


def ensure_llm_config(env_path: Path, *, interactive: bool = True) -> dict[str, str]:
    existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    values = load_dotenv(env_path)
    defaults = {
        "LLM_PROVIDER": values.get("LLM_PROVIDER") or "deepseek",
        "LLM_BASE_URL": values.get("LLM_BASE_URL") or DEEPSEEK_BASE_URL,
        "LLM_MODEL": values.get("LLM_MODEL", ""),
        "LLM_API_KEY": values.get("LLM_API_KEY", ""),
    }
    missing = missing_llm_config(defaults)
    if not missing:
        return defaults
    if not interactive:
        raise RuntimeError(f"Missing LLM config in .env: {', '.join(missing)}")

    print("LLM metadata generation requires configuration.")
    print("Press Enter to accept defaults where shown.")
    for key in LLM_KEYS:
        current = defaults.get(key, "")
        if key not in missing and current:
            continue
        prompt = f"{key}"
        if current:
            prompt += f" [{current}]"
        prompt += ": "
        answer = input(prompt).strip()
        defaults[key] = answer or current

    missing = missing_llm_config(defaults)
    if missing:
        raise RuntimeError(f"Missing LLM config in .env: {', '.join(missing)}")

    content = existing
    for key, value in defaults.items():
        content = _set_env_value(content, key, value)
    env_path.write_text(content, encoding="utf-8")
    return defaults


def write_env_file(python_bin: Path, hugo_bin: Path, env: dict[str, str]) -> Path:
    env_path = PROJECT_ROOT / ".env"
    generated = build_env_content(
        project_root=PROJECT_ROOT,
        python_bin=python_bin,
        hugo_bin=hugo_bin,
        env=env,
    )
    existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    env_path.write_text(merge_env_content(existing=existing, generated=generated), encoding="utf-8")
    return env_path


def enter_shell(env: dict[str, str]) -> None:
    shell = env.get("SHELL") or "/bin/sh"
    print(f"Entering local toolchain shell: {shell}")
    print("Run `exit` to return to the previous shell.")
    os.execvpe(shell, [shell, "-i"], env)


def main() -> int:
    parser = argparse.ArgumentParser(description="Initialize local blog tooling.")
    parser.add_argument(
        "--hugo-version",
        default=os.environ.get("HUGO_VERSION", DEFAULT_HUGO_VERSION),
        help=f"Required Hugo version. Default: {DEFAULT_HUGO_VERSION}",
    )
    parser.add_argument(
        "--no-shell",
        action="store_true",
        help="Initialize only; do not enter the project-local interactive shell.",
    )
    args = parser.parse_args()

    try:
        python_bin = ensure_uv_environment()
        hugo_bin = ensure_hugo(args.hugo_version)
        ensure_llm_config(PROJECT_ROOT / ".env", interactive=not args.no_shell)
        shell_env = build_shell_env(
            base_env=os.environ,
            project_root=PROJECT_ROOT,
            python_bin=python_bin,
            hugo_bin=hugo_bin,
        )
        env_path = write_env_file(python_bin, hugo_bin, shell_env)
    except RuntimeError as exc:
        print(f"init.py: {exc}", file=sys.stderr)
        return 1

    print(f"Environment file written: {env_path}")
    print(f"Python: {python_bin}")
    print(f"Hugo: {hugo_bin}")
    if not args.no_shell:
        enter_shell(shell_env)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
